### ISSUE TITLE
Places Model

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/core-data-cloud#26]
Should have attributes and relations corresponding to everything in the [Linked Places JSON-LD spec](https://github.com/LinkedPasts/linked-places-format).

- [x] #34
- [x] #35
- [ ] Has and belongs to many Sites (parent, child, sibling)
- [ ] Relations to people, organizations, collections, sources, controlled vocabularies
- [ ] Timespans 
- [ ] Types
- [ ] Links
- [ ] Relations
- [ ] Descriptions
- [ ] Depictions (imagery, in our case, likely IIIF media)
